### ISSUE TITLE
Add GitHub Topic: gitlab-backup

### ISSUE THREAD

**Issue by katrinleinweber** [KernelFolla/dumpmyrepos#3]
Thanks for publishing this! In case you'd like to make [your repo more findable](https://github.com/topics/gitlab-backup), you could [add that topic](https://help.github.com/articles/about-topics/) ;-) Thank you!

**Comment by KernelFolla** [comment]
Thank you @katrinleinweber, honestly I've discovered "github topics" thanks to you:)

**Comment by katrinleinweber** [comment]
Cool, you're welcome! Basically the good old Yahoo! Directory ;-)
